### ISSUE TITLE
Can we delete this repository?

### ISSUE THREAD

**Issue by e-perl-NOAA** [nmfs-stock-synthesis/tpl-format#1]
@Rick-Methot-NOAA Can we delete this repository? Do we need it for anything?

**Comment by Rick-Methot-NOAA** [comment]
Code seems useful to keep, but does not need its own repository.

**Comment by e-perl-NOAA** [comment]
@Rick-Methot-NOAA do you mind if I archive this repository?

**Comment by Rick-Methot-NOAA** [comment]
OK to archive after copy content to google drive developers folder.

**Comment by e-perl-NOAA** [comment]
Done, copied to the developers under Archive.
